### ISSUE TITLE
hi cuestion

### ISSUE THREAD

**Issue by turuwhiska** [db-electronics/SMSMapper#1]
hi this mapper work widout A16-A18? replacing flash memory with a rom virtual (quartus)

**Comment by db-electronics** [comment]
I don't understand your question.

**Comment by turuwhiska** [comment]
thanks for your repli!! I'm trying to load a rom from a 10-nano to game gear. create a rom, but gamegear bios only loads the rom with mapper. The rom that quartus create (8bits) is a maximum of 64kb (A0-A15), apparently your mapper needs A16-A18 (256kb?). Can it be implemented with 64kb memory? (A0-A15)

**Comment by sverx** [comment]
Game Gear BIOS doesn't require a mapper, but it requires that your ROM has a header.
Check this: https://www.smspower.org/Development/ROMHeader
Basically you just need `TMR SEGA` written at some specific location.

**Comment by db-electronics** [comment]
If you're using fewer address lines it should only result in mirroring, which shouldn't affect your code negatively at all.

**Comment by turuwhiska** [comment]
I'll try it then and let you know if it works.
